dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

sources:
  - google-chrome
packages:
  - dpkg 
  - google-chrome-stable --allow-unauthenticated

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
before_install:
- pip install --user codecov
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6d0cfb5b-59be-42fe-94f4-9ab5be0c4446

