dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

sources:
  - google-chrome
packages:
  - dpkg 
  - google-chrome-stable --allow-unauthenticated

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

before_install:
- pip install --user codecov
after_success:
- codecov
